image_size: 50
avatar_size_small: 30
avatar_size: 200
avatar_size_edit: 200
image_type_accept: image/jpeg,image/gif,image/png
image_type:
  - jpg
  - jpeg
  - gif
  - png
per_page: 10
limit_activities: 10
complete_task: "Complete task:"
finished: "finished"
finish: "finish"
